#!/bin/sh -eu

. /usr/share/initramfs-tools/scripts/functions
. /usr/share/initramfs-tools/hook-functions

# these binaries used by our "init-bottom-overlay" script
# (or for debug in case init script fails and we drop to shell)

copy_exec /usr/bin/lsblk
copy_exec /usr/bin/base64

# initramfs is also built in early stage of our bootstrap where fscrypt is not yet available.
if [ -f /usr/bin/fscrypt ]; then
	copy_exec /usr/bin/fscrypt

	# the darn fscrypt requires fscrypt.conf to be present even in initramfs
	mkdir -p "${DESTDIR}/etc"
	cp /etc/fscrypt.conf "${DESTDIR}/etc/fscrypt.conf"
	# for some reason this doesn't work
	# copy_file config /etc/fscrypt.conf
fi
