#!/bin/sh

# TODO: document stages of initramfs execution (i.e. what does "init-bottom" mean)
# original: https://github.com/chesty/overlayroot/blob/master/init-bottom-overlay

PREREQ=""
prereqs()
{
   echo "$PREREQ"
}

case $1 in
prereqs)
   prereqs
   exit 0
   ;;
esac

# exports "$rootmnt" etc.
. /scripts/functions

set -eu

log_begin_msg "Setting up root overlay rootmnt=${rootmnt}"

#    "sysid=v1"
# => "v1"
sysId="$(grep -oE 'sysid=[^ ]+' /proc/cmdline | cut -d = -f 2)"
if [ -z "$sysId" ]; then
	panic "failed to resolve sysId"
fi

# in-ram mount point
mkdir -p /sysroot

# move real root
mount --no-mtab -o move "$rootmnt" "/sysroot" || panic "failed mounting $treeSysroot"

mount -t overlay overlay -olowerdir="/sysroot/apps/OS-checkout/${sysId},upperdir=/sysroot/apps/OS-diff/${sysId},workdir=/sysroot/apps/OS-diff/${sysId}-work" /root

mkdir -p /root/sysroot

# expose real root to be accessible from overlaid filesystem
mount --no-mtab -o rbind /sysroot /root/sysroot

log_end_msg

exit 0

# it's important to realize we're NOT creating this tree under the actual root (which is temporarily
# under "$rootmnt"). this is an in-memory tree inside the ramdisk
# mkdir -p /persist

# search fs to use for the persist partition
# the `PARRTYPE` corresponds to "Linux x86-64 root (/)"
# spec: https://uapi-group.org/specifications/specs/discoverable_partitions_specification/
# persistDev=`blkid --list-one --output=device --match-token=PARTLABEL="Linux x86-64 root (/)"`
# this doesn't work for some reason:
# persistDev=`blkid --list-one --output=device --match-token=PARTTYPE="4f68bce3-e8cd-4db1-96e7-fbcaf984b709"`

# if [ ! -z "${persistDev}" ]; then
# 	# _checkfs_once "$persistDev" /persist >> /log.txt 2>&1 ||  \
# 	mount "$persistDev" /persist || panic "failed mounting /persist"
# else
# 	panic "partition with label=persist not found"
# fi

# "\\EFI\systemb\vmlinuz root=LABEL=system_b ro initrd=\EFI\systemb\initrd.img" -> "system_b"
# (busybox grep behaves differently than GNU grep, so we'll use "$ cut" instead of capture group)
# sysId="$(grep -oE 'root=LABEL=[^ ]+' /proc/cmdline | cut -d = -f 3)"
sysId="v1"

if [ -z "$sysId" ]; then
	panic "failed to resolve sysId"
fi

treeCheckout="${rootmnt}/apps/OS-checkout/${sysId}"
treeSysroot="/sysroot"
treeDiff="${rootmnt}/apps/OS-diff/${sysId}"
treeWork="${rootmnt}/apps/OS-diff/${sysId}-work"

# make mount points for readonly root, diff and workdir. (these are persisted on the actual persisted partition)
# usually these already exist, but let's be friendly to the user if she's starting from empty data partition
mkdir -p \
	"$treeSysroot" \
	"$treeDiff" \
	"$treeWork"

# activeSysId="$(cat /persist/apps/SYSTEM_nobackup/active_sys_id)"
activeSysId="v1"

# verify that we're booting the intended system id.
# it can be catastrophic if user accidentally boots the wrong one and continues working for a long time.
if [ ! "$sysId" = "$activeSysId" ]; then
	panic "activeSysId != sys ID you're booting now. edit /persist/apps/SYSTEM_nobackup/active_sys_id if you really want to boot $sysId"
fi

# make the readonly root (TODO: who makes it readonly?) available bypassing the overlayfs
mount --no-mtab -o move "$rootmnt" "$treeSysroot" || panic "failed mounting $treeSysroot"

# TODO: I think we now have two mounts for "$rootmnt", is that ok?
mount -t overlay overlay \
	"-olowerdir=${treeCheckout},upperdir=${treeDiff},workdir=${treeWork}" \
	"$rootmnt" || panic "failed mounting / overlay"

# /sysroot -> /root/sysroot
mount --no-mtab -o move "$treeSysroot" "${rootmnt}${treeSysroot}" || panic "failed moving $treeSysroot"

# now move the purely-in-RAM mount point under the actual root mount
# mkdir -p "${rootmnt}/persist" || panic "failed making /persist dir"

# rbind means recursive
# mount --no-mtab -o rbind /persist "${rootmnt}/persist" || panic "failed binding in-RAM /persist to rootfs /persist"

# root was like this:
# 	/dev/sda / ext4  errors=remount-ro 0 1
# make it look like this:
# 	overlay / overlay rw,relative,lowerdir=/persist/sys-current-rom,upperdir=/persist/sys-a-diff,workdir=/persist/.sys-a-work 0 0

# TODO: what's this do exactly? it's not just a backup, since it's used by AWK
# cp "${rootmnt}/etc/fstab" "${rootmnt}/etc/fstab.orig"

# awk '$2 != "/" {print $0}' "${rootmnt}/etc/fstab.orig" > "${rootmnt}/etc/fstab"
# awk '$2 == "'${rootmnt}'" { $2 = "/" ; print $0}' /etc/mtab >> "${rootmnt}/etc/fstab"

log_end_msg
