version: '3'
services:
  tailscale:
    restart: unless-stopped
    image: tailscale/tailscale:v1.34.2
    environment:
    # without this, uses "--state=mem" and uses ephemeral nodes
    - TS_STATE_DIR=/var/lib/tailscale
    - TS_SOCKET=/var/run/tailscale/tailscaled.sock
    # defaults to true. ip routes don't get installed etc. maybe Tailscale isn't designed to work in a container in this manner
    # because we seem to be needing quite a bunch of overrides..
    - TS_USERSPACE=false
    devices:
    - /dev/net/tun
    # TODO: reduce to individual caps
    privileged: true
    network_mode: host
    volumes:
    - /persist/apps/tailscale-state:/var/lib/tailscale
    - /var/run/tailscale:/var/run/tailscale

