daemonize = false
max_history = 50          # max clip history limit
log_level = 'INFO'        # log level

[monitor]
load_current = true       # load current clipboard content at startup
enable_clipboard = true   # watch X11 clipboard
enable_primary = true     # watch X11 primary clipboard

[grpc]
host = '127.0.0.1'        # host address for gRPC
port = 45045              # port number for gRPC

